// Generated by CIRCT firtool-1.139.0
module ALU(
  input  [3:0]  io_op,
  input  [31:0] io_in1,
                io_in2,
  output [31:0] io_out
);

  wire        _io_out_T_1 = io_op == 4'h1;
  wire [62:0] sll_result = {31'h0, io_in1} << io_in2[4:0];
  wire [31:0] _GEN = {27'h0, io_in2[4:0]};
  assign io_out =
    io_op == 4'h0 | _io_out_T_1
      ? io_in1 + (_io_out_T_1 ? 32'h0 - io_in2 : io_in2)
      : io_op == 4'h2
          ? io_in1 & io_in2
          : io_op == 4'h3
              ? io_in1 | io_in2
              : io_op == 4'h4
                  ? io_in1 ^ io_in2
                  : io_op == 4'h5
                      ? {31'h0, $signed(io_in1) < $signed(io_in2)}
                      : io_op == 4'h6
                          ? {31'h0, io_in1 < io_in2}
                          : io_op == 4'h7
                              ? sll_result[31:0]
                              : io_op == 4'h8
                                  ? io_in1 >> _GEN
                                  : io_op == 4'h9
                                      ? $signed($signed(io_in1) >>> _GEN)
                                      : io_in1;
endmodule

