// Generated by CIRCT firtool-1.139.0
module Decoder(
  input  [31:0] io_inst,
  output [1:0]  io_ctrl_op1_sel,
  output [2:0]  io_ctrl_op2_sel,
  output [3:0]  io_ctrl_alu_op,
  output [1:0]  io_ctrl_fu_sel,
  output [2:0]  io_ctrl_branch_type,
  output        io_ctrl_mem_en,
                io_ctrl_mem_rw,
  output [2:0]  io_ctrl_mem_type,
  output [1:0]  io_ctrl_wb_sel,
  output        io_ctrl_reg_write,
  output [2:0]  io_ctrl_imm_type
);

  wire [9:0]  _GEN = {io_inst[14:12], io_inst[6:0]};
  wire        _cs_T_1 = _GEN == 10'h103;
  wire        _cs_T_3 = _GEN == 10'h83;
  wire        _cs_T_5 = _GEN == 10'h283;
  wire        _cs_T_7 = _GEN == 10'h3;
  wire        _cs_T_9 = _GEN == 10'h203;
  wire        _cs_T_11 = _GEN == 10'h123;
  wire        _cs_T_13 = _GEN == 10'hA3;
  wire        _cs_T_15 = _GEN == 10'h23;
  wire        _cs_T_17 = _GEN == 10'h13;
  wire        _cs_T_19 = _GEN == 10'h113;
  wire        _cs_T_21 = _GEN == 10'h193;
  wire        _cs_T_23 = _GEN == 10'h393;
  wire        _cs_T_25 = _GEN == 10'h313;
  wire        _cs_T_27 = _GEN == 10'h213;
  wire [15:0] _GEN_0 = {io_inst[31:26], io_inst[14:12], io_inst[6:0]};
  wire        _cs_T_29 = _GEN_0 == 16'h93;
  wire        _cs_T_31 = _GEN_0 == 16'h293;
  wire        _cs_T_33 = _GEN_0 == 16'h4293;
  wire [16:0] _GEN_1 = {io_inst[31:25], io_inst[14:12], io_inst[6:0]};
  wire        _cs_T_35 = _GEN_1 == 17'h33;
  wire        _cs_T_37 = _GEN_1 == 17'h8033;
  wire        _cs_T_39 = _GEN_1 == 17'h133;
  wire        _cs_T_41 = _GEN_1 == 17'h1B3;
  wire        _cs_T_43 = _GEN_1 == 17'h3B3;
  wire        _cs_T_45 = _GEN_1 == 17'h333;
  wire        _cs_T_47 = _GEN_1 == 17'h233;
  wire        _cs_T_49 = _GEN_1 == 17'hB3;
  wire        _cs_T_51 = _GEN_1 == 17'h2B3;
  wire        _cs_T_53 = _GEN_1 == 17'h82B3;
  wire        _cs_T_55 = io_inst[6:0] == 7'h37;
  wire        _cs_T_57 = io_inst[6:0] == 7'h17;
  wire        _cs_T_59 = _GEN == 10'h63;
  wire        _cs_T_61 = _GEN == 10'hE3;
  wire        _cs_T_63 = _GEN == 10'h263;
  wire        _cs_T_65 = _GEN == 10'h2E3;
  wire        _cs_T_67 = _GEN == 10'h363;
  wire        _cs_T_69 = _GEN == 10'h3E3;
  wire        _cs_T_71 = io_inst[6:0] == 7'h6F;
  wire        _cs_T_434 = _GEN == 10'h67;
  wire        _GEN_2 =
    _cs_T_35 | _cs_T_37 | _cs_T_39 | _cs_T_41 | _cs_T_43 | _cs_T_45 | _cs_T_47 | _cs_T_49
    | _cs_T_51 | _cs_T_53;
  wire        _GEN_3 = _cs_T_71 | _cs_T_434;
  wire        _GEN_4 =
    _cs_T_55 | _cs_T_57 | _cs_T_59 | _cs_T_61 | _cs_T_63 | _cs_T_65 | _cs_T_67 | _cs_T_69
    | _GEN_3;
  wire        _GEN_5 =
    _cs_T_17 | _cs_T_19 | _cs_T_21 | _cs_T_23 | _cs_T_25 | _cs_T_27 | _cs_T_29 | _cs_T_31
    | _cs_T_33;
  wire        _GEN_6 = _cs_T_59 | _cs_T_61 | _cs_T_63 | _cs_T_65 | _cs_T_67 | _cs_T_69;
  wire        _GEN_7 = _cs_T_55 | _cs_T_57;
  wire        _GEN_8 = _cs_T_11 | _cs_T_13 | _cs_T_15;
  wire        _GEN_9 = _cs_T_1 | _cs_T_3 | _cs_T_5 | _cs_T_7 | _cs_T_9;
  wire        _GEN_10 =
    _cs_T_17 | _cs_T_19 | _cs_T_21 | _cs_T_23 | _cs_T_25 | _cs_T_27 | _cs_T_29 | _cs_T_31
    | _cs_T_33 | _cs_T_35 | _cs_T_37 | _cs_T_39 | _cs_T_41 | _cs_T_43 | _cs_T_45
    | _cs_T_47 | _cs_T_49 | _cs_T_51 | _cs_T_53 | _GEN_7;
  wire [1:0]  cs_11 = _GEN_9 ? 2'h1 : {_GEN_8, 1'h0};
  assign io_ctrl_op1_sel =
    _cs_T_1 | _cs_T_3 | _cs_T_5 | _cs_T_7 | _cs_T_9 | _cs_T_11 | _cs_T_13 | _cs_T_15
    | _cs_T_17 | _cs_T_19 | _cs_T_21 | _cs_T_23 | _cs_T_25 | _cs_T_27 | _cs_T_29
    | _cs_T_31 | _cs_T_33 | _GEN_2
      ? 2'h1
      : _cs_T_55
          ? 2'h3
          : _cs_T_57 | _cs_T_59 | _cs_T_61 | _cs_T_63 | _cs_T_65 | _cs_T_67 | _cs_T_69
            | _cs_T_71
              ? 2'h2
              : {1'h0, _cs_T_434};
  assign io_ctrl_op2_sel =
    _cs_T_1 | _cs_T_3 | _cs_T_5 | _cs_T_7 | _cs_T_9 | _cs_T_11 | _cs_T_13 | _cs_T_15
    | _GEN_5
      ? 3'h2
      : _GEN_2 ? 3'h1 : {1'h0, _GEN_4, 1'h0};
  assign io_ctrl_alu_op =
    _cs_T_1 | _cs_T_3 | _cs_T_5 | _cs_T_7 | _cs_T_9 | _cs_T_11 | _cs_T_13 | _cs_T_15
    | _cs_T_17
      ? 4'h0
      : _cs_T_19
          ? 4'h5
          : _cs_T_21
              ? 4'h6
              : _cs_T_23
                  ? 4'h2
                  : _cs_T_25
                      ? 4'h3
                      : _cs_T_27
                          ? 4'h4
                          : _cs_T_29
                              ? 4'h7
                              : _cs_T_31
                                  ? 4'h8
                                  : _cs_T_33
                                      ? 4'h9
                                      : _cs_T_35
                                          ? 4'h0
                                          : _cs_T_37
                                              ? 4'h1
                                              : _cs_T_39
                                                  ? 4'h5
                                                  : _cs_T_41
                                                      ? 4'h6
                                                      : _cs_T_43
                                                          ? 4'h2
                                                          : _cs_T_45
                                                              ? 4'h3
                                                              : _cs_T_47
                                                                  ? 4'h4
                                                                  : _cs_T_49
                                                                      ? 4'h7
                                                                      : _cs_T_51
                                                                          ? 4'h8
                                                                          : _cs_T_53
                                                                              ? 4'h9
                                                                              : _GEN_4
                                                                                  ? 4'h0
                                                                                  : 4'hF;
  assign io_ctrl_fu_sel =
    {_cs_T_1 | _cs_T_3 | _cs_T_5 | _cs_T_7 | _cs_T_9 | _GEN_8, 1'h0};
  assign io_ctrl_branch_type =
    _cs_T_1 | _cs_T_3 | _cs_T_5 | _cs_T_7 | _cs_T_9 | _cs_T_11 | _cs_T_13 | _cs_T_15
    | _GEN_10
      ? 3'h0
      : _cs_T_59
          ? 3'h1
          : _cs_T_61
              ? 3'h2
              : _cs_T_63
                  ? 3'h3
                  : _cs_T_65 ? 3'h5 : _cs_T_67 ? 3'h4 : _cs_T_69 ? 3'h6 : {3{_GEN_3}};
  assign io_ctrl_mem_en = |cs_11;
  assign io_ctrl_mem_rw = cs_11 == 2'h2;
  assign io_ctrl_mem_type =
    _cs_T_1
      ? 3'h3
      : _cs_T_3
          ? 3'h2
          : _cs_T_5
              ? 3'h5
              : _cs_T_7
                  ? 3'h1
                  : _cs_T_9 ? 3'h4 : _cs_T_11 ? 3'h3 : _cs_T_13 ? 3'h2 : {2'h0, _cs_T_15};
  assign io_ctrl_wb_sel =
    _GEN_9 ? 2'h2 : _GEN_8 ? 2'h0 : _GEN_10 ? 2'h1 : _GEN_6 ? 2'h0 : {2{_GEN_3}};
  assign io_ctrl_reg_write =
    _GEN_9 | ~_GEN_8 & (_GEN_10 | ~_GEN_6 & (_cs_T_71 | _cs_T_434));
  assign io_ctrl_imm_type =
    _GEN_9
      ? 3'h1
      : _GEN_8
          ? 3'h2
          : _GEN_5
              ? 3'h1
              : _GEN_2
                  ? 3'h0
                  : _GEN_7 ? 3'h4 : _GEN_6 ? 3'h3 : _cs_T_71 ? 3'h5 : {2'h0, _cs_T_434};
endmodule

