// Generated by CIRCT firtool-1.139.0
module DecodeStage(
  input         clock,
  input  [31:0] io_ifid_pc,
                io_ifid_inst,
  input         io_ifid_valid,
  input  [4:0]  io_wb_rd_addr,
  input  [31:0] io_wb_rd_data,
  input         io_wb_reg_write,
  output [31:0] io_idex_pc,
  output        io_idex_valid,
  output [4:0]  io_idex_rd_addr,
  output [31:0] io_idex_rs1_data,
                io_idex_rs2_data,
                io_idex_imm,
  output [1:0]  io_idex_op1_sel,
  output [2:0]  io_idex_op2_sel,
  output [3:0]  io_idex_alu_op,
  output [1:0]  io_idex_fu_sel,
  output [2:0]  io_idex_branch_type,
  output        io_idex_mem_en,
                io_idex_mem_rw,
  output [2:0]  io_idex_mem_type,
  output [1:0]  io_idex_wb_sel,
  output        io_idex_reg_write
);

  wire [2:0] _decoder_io_ctrl_imm_type;
  Decoder decoder (
    .io_inst             (io_ifid_inst),
    .io_ctrl_op1_sel     (io_idex_op1_sel),
    .io_ctrl_op2_sel     (io_idex_op2_sel),
    .io_ctrl_alu_op      (io_idex_alu_op),
    .io_ctrl_fu_sel      (io_idex_fu_sel),
    .io_ctrl_branch_type (io_idex_branch_type),
    .io_ctrl_mem_en      (io_idex_mem_en),
    .io_ctrl_mem_rw      (io_idex_mem_rw),
    .io_ctrl_mem_type    (io_idex_mem_type),
    .io_ctrl_wb_sel      (io_idex_wb_sel),
    .io_ctrl_reg_write   (io_idex_reg_write),
    .io_ctrl_imm_type    (_decoder_io_ctrl_imm_type)
  );
  ImmGen immgen (
    .io_inst (io_ifid_inst),
    .io_sel  (_decoder_io_ctrl_imm_type),
    .io_out  (io_idex_imm)
  );
  RegisterFile regfile (
    .clock       (clock),
    .io_rs1_addr (io_ifid_inst[19:15]),
    .io_rs2_addr (io_ifid_inst[24:20]),
    .io_rd_addr  (io_wb_rd_addr),
    .io_rd_data  (io_wb_rd_data),
    .io_wen      (io_wb_reg_write),
    .io_rs1_data (io_idex_rs1_data),
    .io_rs2_data (io_idex_rs2_data)
  );
  assign io_idex_pc = io_ifid_pc;
  assign io_idex_valid = io_ifid_valid;
  assign io_idex_rd_addr = io_ifid_inst[11:7];
endmodule

