// Generated by CIRCT firtool-1.139.0
module FetchStage(
  input         clock,
                reset,
  input  [31:0] io_pc_next,
  input         io_pc_we,
  output [31:0] io_inst_req_addr,
  input  [31:0] io_inst_resp_rdata,
  input         io_inst_resp_valid,
  output [31:0] io_ifid_pc,
                io_ifid_inst,
  output        io_ifid_valid,
  output [31:0] io_pc
);

  reg [31:0] pc_reg;
  always @(posedge clock) begin
    if (reset)
      pc_reg <= 32'h80000000;
    else
      pc_reg <= io_pc_we ? io_pc_next : pc_reg + 32'h4;
  end // always @(posedge)
  assign io_inst_req_addr = pc_reg;
  assign io_ifid_pc = pc_reg;
  assign io_ifid_inst = io_inst_resp_rdata;
  assign io_ifid_valid = io_inst_resp_valid;
  assign io_pc = pc_reg;
endmodule

