// Generated by CIRCT firtool-1.139.0
module ImmGen(
  input  [31:0] io_inst,
  input  [2:0]  io_sel,
  output [31:0] io_out
);

  wire [7:0][31:0] _GEN =
    {{32'h0},
     {{27'h0, io_inst[19:15]}},
     {{{12{io_inst[31]}}, io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}},
     {{io_inst[31:12], 12'h0}},
     {{{20{io_inst[31]}}, io_inst[7], io_inst[30:25], io_inst[11:8], 1'h0}},
     {{{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}},
     {{{20{io_inst[31]}}, io_inst[31:20]}},
     {32'h0}};
  assign io_out = _GEN[io_sel];
endmodule

