// Generated by CIRCT firtool-1.139.0
module NeoRV32Core(
  input         clock,
                reset,
  output [31:0] io_imem_req_addr,
  input  [31:0] io_imem_resp_rdata,
  input         io_imem_resp_valid,
  output [31:0] io_dmem_req_addr,
                io_dmem_req_wdata,
  output        io_dmem_req_wen,
  output [3:0]  io_dmem_req_mask,
  output        io_dmem_req_valid,
  input  [31:0] io_dmem_resp_rdata,
  output [31:0] io_debug_pc
);

  wire [4:0]  _writeback_io_wb_rd_addr;
  wire [31:0] _writeback_io_wb_rd_data;
  wire        _writeback_io_wb_reg_write;
  wire [31:0] _memory_io_memwb_pc;
  wire        _memory_io_memwb_valid;
  wire [4:0]  _memory_io_memwb_rd_addr;
  wire [31:0] _memory_io_memwb_alu_result;
  wire [31:0] _memory_io_memwb_mem_rdata;
  wire [1:0]  _memory_io_memwb_wb_sel;
  wire        _memory_io_memwb_reg_write;
  wire [31:0] _execute_io_exmem_pc;
  wire        _execute_io_exmem_valid;
  wire [4:0]  _execute_io_exmem_rd_addr;
  wire [31:0] _execute_io_exmem_alu_result;
  wire [31:0] _execute_io_exmem_rs2_data;
  wire        _execute_io_exmem_mem_en;
  wire        _execute_io_exmem_mem_rw;
  wire [2:0]  _execute_io_exmem_mem_type;
  wire [1:0]  _execute_io_exmem_wb_sel;
  wire        _execute_io_exmem_reg_write;
  wire [31:0] _execute_io_pc_target;
  wire        _execute_io_pc_take;
  wire [31:0] _decode_io_idex_pc;
  wire        _decode_io_idex_valid;
  wire [4:0]  _decode_io_idex_rd_addr;
  wire [31:0] _decode_io_idex_rs1_data;
  wire [31:0] _decode_io_idex_rs2_data;
  wire [31:0] _decode_io_idex_imm;
  wire [1:0]  _decode_io_idex_op1_sel;
  wire [2:0]  _decode_io_idex_op2_sel;
  wire [3:0]  _decode_io_idex_alu_op;
  wire [1:0]  _decode_io_idex_fu_sel;
  wire [2:0]  _decode_io_idex_branch_type;
  wire        _decode_io_idex_mem_en;
  wire        _decode_io_idex_mem_rw;
  wire [2:0]  _decode_io_idex_mem_type;
  wire [1:0]  _decode_io_idex_wb_sel;
  wire        _decode_io_idex_reg_write;
  wire [31:0] _fetch_io_ifid_pc;
  wire [31:0] _fetch_io_ifid_inst;
  wire        _fetch_io_ifid_valid;
  wire [31:0] _fetch_io_pc;
  FetchStage fetch (
    .clock              (clock),
    .reset              (reset),
    .io_pc_next
      (_execute_io_pc_take ? _execute_io_pc_target : _fetch_io_pc + 32'h4),
    .io_pc_we           (_execute_io_pc_take),
    .io_inst_req_addr   (io_imem_req_addr),
    .io_inst_resp_rdata (io_imem_resp_rdata),
    .io_inst_resp_valid (io_imem_resp_valid),
    .io_ifid_pc         (_fetch_io_ifid_pc),
    .io_ifid_inst       (_fetch_io_ifid_inst),
    .io_ifid_valid      (_fetch_io_ifid_valid),
    .io_pc              (_fetch_io_pc)
  );
  DecodeStage decode (
    .clock               (clock),
    .io_ifid_pc          (_fetch_io_ifid_pc),
    .io_ifid_inst        (_fetch_io_ifid_inst),
    .io_ifid_valid       (_fetch_io_ifid_valid),
    .io_wb_rd_addr       (_writeback_io_wb_rd_addr),
    .io_wb_rd_data       (_writeback_io_wb_rd_data),
    .io_wb_reg_write     (_writeback_io_wb_reg_write),
    .io_idex_pc          (_decode_io_idex_pc),
    .io_idex_valid       (_decode_io_idex_valid),
    .io_idex_rd_addr     (_decode_io_idex_rd_addr),
    .io_idex_rs1_data    (_decode_io_idex_rs1_data),
    .io_idex_rs2_data    (_decode_io_idex_rs2_data),
    .io_idex_imm         (_decode_io_idex_imm),
    .io_idex_op1_sel     (_decode_io_idex_op1_sel),
    .io_idex_op2_sel     (_decode_io_idex_op2_sel),
    .io_idex_alu_op      (_decode_io_idex_alu_op),
    .io_idex_fu_sel      (_decode_io_idex_fu_sel),
    .io_idex_branch_type (_decode_io_idex_branch_type),
    .io_idex_mem_en      (_decode_io_idex_mem_en),
    .io_idex_mem_rw      (_decode_io_idex_mem_rw),
    .io_idex_mem_type    (_decode_io_idex_mem_type),
    .io_idex_wb_sel      (_decode_io_idex_wb_sel),
    .io_idex_reg_write   (_decode_io_idex_reg_write)
  );
  ExecuteStage execute (
    .clock               (clock),
    .reset               (reset),
    .io_idex_pc          (_decode_io_idex_pc),
    .io_idex_valid       (_decode_io_idex_valid),
    .io_idex_rd_addr     (_decode_io_idex_rd_addr),
    .io_idex_rs1_data    (_decode_io_idex_rs1_data),
    .io_idex_rs2_data    (_decode_io_idex_rs2_data),
    .io_idex_imm         (_decode_io_idex_imm),
    .io_idex_op1_sel     (_decode_io_idex_op1_sel),
    .io_idex_op2_sel     (_decode_io_idex_op2_sel),
    .io_idex_alu_op      (_decode_io_idex_alu_op),
    .io_idex_fu_sel      (_decode_io_idex_fu_sel),
    .io_idex_branch_type (_decode_io_idex_branch_type),
    .io_idex_mem_en      (_decode_io_idex_mem_en),
    .io_idex_mem_rw      (_decode_io_idex_mem_rw),
    .io_idex_mem_type    (_decode_io_idex_mem_type),
    .io_idex_wb_sel      (_decode_io_idex_wb_sel),
    .io_idex_reg_write   (_decode_io_idex_reg_write),
    .io_exmem_pc         (_execute_io_exmem_pc),
    .io_exmem_valid      (_execute_io_exmem_valid),
    .io_exmem_rd_addr    (_execute_io_exmem_rd_addr),
    .io_exmem_alu_result (_execute_io_exmem_alu_result),
    .io_exmem_rs2_data   (_execute_io_exmem_rs2_data),
    .io_exmem_mem_en     (_execute_io_exmem_mem_en),
    .io_exmem_mem_rw     (_execute_io_exmem_mem_rw),
    .io_exmem_mem_type   (_execute_io_exmem_mem_type),
    .io_exmem_wb_sel     (_execute_io_exmem_wb_sel),
    .io_exmem_reg_write  (_execute_io_exmem_reg_write),
    .io_pc_target        (_execute_io_pc_target),
    .io_pc_take          (_execute_io_pc_take)
  );
  MemoryStage memory (
    .clock               (clock),
    .reset               (reset),
    .io_exmem_pc         (_execute_io_exmem_pc),
    .io_exmem_valid      (_execute_io_exmem_valid),
    .io_exmem_rd_addr    (_execute_io_exmem_rd_addr),
    .io_exmem_alu_result (_execute_io_exmem_alu_result),
    .io_exmem_rs2_data   (_execute_io_exmem_rs2_data),
    .io_exmem_mem_en     (_execute_io_exmem_mem_en),
    .io_exmem_mem_rw     (_execute_io_exmem_mem_rw),
    .io_exmem_mem_type   (_execute_io_exmem_mem_type),
    .io_exmem_wb_sel     (_execute_io_exmem_wb_sel),
    .io_exmem_reg_write  (_execute_io_exmem_reg_write),
    .io_data_req_addr    (io_dmem_req_addr),
    .io_data_req_wdata   (io_dmem_req_wdata),
    .io_data_req_wen     (io_dmem_req_wen),
    .io_data_req_mask    (io_dmem_req_mask),
    .io_data_req_valid   (io_dmem_req_valid),
    .io_data_resp_rdata  (io_dmem_resp_rdata),
    .io_memwb_pc         (_memory_io_memwb_pc),
    .io_memwb_valid      (_memory_io_memwb_valid),
    .io_memwb_rd_addr    (_memory_io_memwb_rd_addr),
    .io_memwb_alu_result (_memory_io_memwb_alu_result),
    .io_memwb_mem_rdata  (_memory_io_memwb_mem_rdata),
    .io_memwb_wb_sel     (_memory_io_memwb_wb_sel),
    .io_memwb_reg_write  (_memory_io_memwb_reg_write)
  );
  WritebackStage writeback (
    .io_memwb_pc         (_memory_io_memwb_pc),
    .io_memwb_valid      (_memory_io_memwb_valid),
    .io_memwb_rd_addr    (_memory_io_memwb_rd_addr),
    .io_memwb_alu_result (_memory_io_memwb_alu_result),
    .io_memwb_mem_rdata  (_memory_io_memwb_mem_rdata),
    .io_memwb_wb_sel     (_memory_io_memwb_wb_sel),
    .io_memwb_reg_write  (_memory_io_memwb_reg_write),
    .io_wb_rd_addr       (_writeback_io_wb_rd_addr),
    .io_wb_rd_data       (_writeback_io_wb_rd_data),
    .io_wb_reg_write     (_writeback_io_wb_reg_write)
  );
  assign io_debug_pc = _fetch_io_pc;
endmodule

