// Generated by CIRCT firtool-1.139.0
module RegisterFile(
  input         clock,
  input  [4:0]  io_rs1_addr,
                io_rs2_addr,
                io_rd_addr,
  input  [31:0] io_rd_data,
  input         io_wen,
  output [31:0] io_rs1_data,
                io_rs2_data
);

  wire [31:0] _rf_ext_R0_data;
  wire [31:0] _rf_ext_R1_data;
  rf_32x32 rf_ext (
    .R0_addr (io_rs2_addr),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_rf_ext_R0_data),
    .R1_addr (io_rs1_addr),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_rf_ext_R1_data),
    .W0_addr (io_rd_addr),
    .W0_en   (io_wen & (|io_rd_addr)),
    .W0_clk  (clock),
    .W0_data (io_rd_data)
  );
  assign io_rs1_data = io_rs1_addr == 5'h0 ? 32'h0 : _rf_ext_R1_data;
  assign io_rs2_data = io_rs2_addr == 5'h0 ? 32'h0 : _rf_ext_R0_data;
endmodule

