// Generated by CIRCT firtool-1.139.0
module WritebackStage(
  input  [31:0] io_memwb_pc,
  input         io_memwb_valid,
  input  [4:0]  io_memwb_rd_addr,
  input  [31:0] io_memwb_alu_result,
                io_memwb_mem_rdata,
  input  [1:0]  io_memwb_wb_sel,
  input         io_memwb_reg_write,
  output [4:0]  io_wb_rd_addr,
  output [31:0] io_wb_rd_data,
  output        io_wb_reg_write
);

  assign io_wb_rd_addr = io_memwb_rd_addr;
  assign io_wb_rd_data =
    io_memwb_wb_sel == 2'h2
      ? io_memwb_mem_rdata
      : (&io_memwb_wb_sel) ? io_memwb_pc + 32'h4 : io_memwb_alu_result;
  assign io_wb_reg_write = io_memwb_reg_write & io_memwb_valid;
endmodule

