// Generated by CIRCT firtool-1.139.0
module DecodeStage(
  input         clock,
                reset,
  input  [31:0] io_ifid_pc,
                io_ifid_inst,
  input         io_ifid_valid,
  input  [4:0]  io_wb_rd_addr,
  input  [31:0] io_wb_rd_data,
  input         io_wb_reg_write,
  output [31:0] io_idex_pc,
  output        io_idex_valid,
  output [4:0]  io_idex_rd_addr,
  output [31:0] io_idex_rs1_data,
                io_idex_rs2_data,
                io_idex_imm,
  output [1:0]  io_idex_op1_sel,
  output [2:0]  io_idex_op2_sel,
  output [3:0]  io_idex_alu_op,
  output [2:0]  io_idex_branch_type,
  output        io_idex_mem_en,
                io_idex_mem_rw,
  output [1:0]  io_idex_wb_sel,
  output        io_idex_reg_write
);

  wire [31:0] _regfile_io_rs1_data;
  wire [31:0] _regfile_io_rs2_data;
  wire [31:0] _immgen_io_out;
  wire [1:0]  _decoder_io_ctrl_op1_sel;
  wire [2:0]  _decoder_io_ctrl_op2_sel;
  wire [3:0]  _decoder_io_ctrl_alu_op;
  wire [2:0]  _decoder_io_ctrl_branch_type;
  wire        _decoder_io_ctrl_mem_en;
  wire        _decoder_io_ctrl_mem_rw;
  wire [1:0]  _decoder_io_ctrl_wb_sel;
  wire        _decoder_io_ctrl_reg_write;
  wire [2:0]  _decoder_io_ctrl_imm_type;
  reg  [31:0] idex_reg_pc;
  reg         idex_reg_valid;
  reg  [4:0]  idex_reg_rd_addr;
  reg  [31:0] idex_reg_rs1_data;
  reg  [31:0] idex_reg_rs2_data;
  reg  [31:0] idex_reg_imm;
  reg  [1:0]  idex_reg_op1_sel;
  reg  [2:0]  idex_reg_op2_sel;
  reg  [3:0]  idex_reg_alu_op;
  reg  [2:0]  idex_reg_branch_type;
  reg         idex_reg_mem_en;
  reg         idex_reg_mem_rw;
  reg  [1:0]  idex_reg_wb_sel;
  reg         idex_reg_reg_write;
  always @(posedge clock) begin
    if (reset) begin
      idex_reg_pc <= 32'h0;
      idex_reg_valid <= 1'h0;
      idex_reg_rd_addr <= 5'h0;
      idex_reg_rs1_data <= 32'h0;
      idex_reg_rs2_data <= 32'h0;
      idex_reg_imm <= 32'h0;
      idex_reg_op1_sel <= 2'h0;
      idex_reg_op2_sel <= 3'h0;
      idex_reg_alu_op <= 4'h0;
      idex_reg_branch_type <= 3'h0;
      idex_reg_mem_en <= 1'h0;
      idex_reg_mem_rw <= 1'h0;
      idex_reg_wb_sel <= 2'h0;
      idex_reg_reg_write <= 1'h0;
    end
    else begin
      idex_reg_pc <= io_ifid_pc;
      idex_reg_valid <= io_ifid_valid;
      idex_reg_rd_addr <= io_ifid_inst[11:7];
      idex_reg_rs1_data <= _regfile_io_rs1_data;
      idex_reg_rs2_data <= _regfile_io_rs2_data;
      idex_reg_imm <= _immgen_io_out;
      idex_reg_op1_sel <= _decoder_io_ctrl_op1_sel;
      idex_reg_op2_sel <= _decoder_io_ctrl_op2_sel;
      idex_reg_alu_op <= _decoder_io_ctrl_alu_op;
      idex_reg_branch_type <= _decoder_io_ctrl_branch_type;
      idex_reg_mem_en <= _decoder_io_ctrl_mem_en;
      idex_reg_mem_rw <= _decoder_io_ctrl_mem_rw;
      idex_reg_wb_sel <= _decoder_io_ctrl_wb_sel;
      idex_reg_reg_write <= _decoder_io_ctrl_reg_write;
    end
  end // always @(posedge)
  Decoder decoder (
    .io_inst             (io_ifid_inst),
    .io_ctrl_op1_sel     (_decoder_io_ctrl_op1_sel),
    .io_ctrl_op2_sel     (_decoder_io_ctrl_op2_sel),
    .io_ctrl_alu_op      (_decoder_io_ctrl_alu_op),
    .io_ctrl_branch_type (_decoder_io_ctrl_branch_type),
    .io_ctrl_mem_en      (_decoder_io_ctrl_mem_en),
    .io_ctrl_mem_rw      (_decoder_io_ctrl_mem_rw),
    .io_ctrl_wb_sel      (_decoder_io_ctrl_wb_sel),
    .io_ctrl_reg_write   (_decoder_io_ctrl_reg_write),
    .io_ctrl_imm_type    (_decoder_io_ctrl_imm_type)
  );
  ImmGen immgen (
    .io_inst (io_ifid_inst),
    .io_sel  (_decoder_io_ctrl_imm_type),
    .io_out  (_immgen_io_out)
  );
  RegisterFile regfile (
    .clock       (clock),
    .io_rs1_addr (io_ifid_inst[19:15]),
    .io_rs2_addr (io_ifid_inst[24:20]),
    .io_rd_addr  (io_wb_rd_addr),
    .io_rd_data  (io_wb_rd_data),
    .io_wen      (io_wb_reg_write),
    .io_rs1_data (_regfile_io_rs1_data),
    .io_rs2_data (_regfile_io_rs2_data)
  );
  assign io_idex_pc = idex_reg_pc;
  assign io_idex_valid = idex_reg_valid;
  assign io_idex_rd_addr = idex_reg_rd_addr;
  assign io_idex_rs1_data = idex_reg_rs1_data;
  assign io_idex_rs2_data = idex_reg_rs2_data;
  assign io_idex_imm = idex_reg_imm;
  assign io_idex_op1_sel = idex_reg_op1_sel;
  assign io_idex_op2_sel = idex_reg_op2_sel;
  assign io_idex_alu_op = idex_reg_alu_op;
  assign io_idex_branch_type = idex_reg_branch_type;
  assign io_idex_mem_en = idex_reg_mem_en;
  assign io_idex_mem_rw = idex_reg_mem_rw;
  assign io_idex_wb_sel = idex_reg_wb_sel;
  assign io_idex_reg_write = idex_reg_reg_write;
endmodule

