// Generated by CIRCT firtool-1.139.0
module ExecuteStage(
  input         clock,
                reset,
  input  [31:0] io_idex_pc,
  input         io_idex_valid,
  input  [4:0]  io_idex_rd_addr,
  input  [31:0] io_idex_rs1_data,
                io_idex_rs2_data,
                io_idex_imm,
  input  [1:0]  io_idex_op1_sel,
  input  [2:0]  io_idex_op2_sel,
  input  [3:0]  io_idex_alu_op,
  input  [2:0]  io_idex_branch_type,
  input         io_idex_mem_en,
                io_idex_mem_rw,
  input  [1:0]  io_idex_wb_sel,
  input         io_idex_reg_write,
  output [31:0] io_exmem_pc,
  output        io_exmem_valid,
  output [4:0]  io_exmem_rd_addr,
  output [31:0] io_exmem_alu_result,
                io_exmem_rs2_data,
  output        io_exmem_mem_en,
                io_exmem_mem_rw,
  output [1:0]  io_exmem_wb_sel,
  output        io_exmem_reg_write,
  output [31:0] io_pc_target,
  output        io_pc_take
);

  wire [31:0] _alu_io_out;
  wire [7:0]  _GEN =
    {{&io_idex_branch_type},
     {io_idex_rs1_data >= io_idex_rs2_data},
     {$signed(io_idex_rs1_data) >= $signed(io_idex_rs2_data)},
     {io_idex_rs1_data < io_idex_rs2_data},
     {$signed(io_idex_rs1_data) < $signed(io_idex_rs2_data)},
     {io_idex_rs1_data != io_idex_rs2_data},
     {io_idex_rs1_data == io_idex_rs2_data},
     {&io_idex_branch_type}};
  wire [31:0] _jalr_target_T = io_idex_rs1_data + io_idex_imm;
  reg  [31:0] exmem_reg_pc;
  reg         exmem_reg_valid;
  reg  [4:0]  exmem_reg_rd_addr;
  reg  [31:0] exmem_reg_alu_result;
  reg  [31:0] exmem_reg_rs2_data;
  reg         exmem_reg_mem_en;
  reg         exmem_reg_mem_rw;
  reg  [1:0]  exmem_reg_wb_sel;
  reg         exmem_reg_reg_write;
  always @(posedge clock) begin
    if (reset) begin
      exmem_reg_pc <= 32'h0;
      exmem_reg_valid <= 1'h0;
      exmem_reg_rd_addr <= 5'h0;
      exmem_reg_alu_result <= 32'h0;
      exmem_reg_rs2_data <= 32'h0;
      exmem_reg_mem_en <= 1'h0;
      exmem_reg_mem_rw <= 1'h0;
      exmem_reg_wb_sel <= 2'h0;
      exmem_reg_reg_write <= 1'h0;
    end
    else begin
      exmem_reg_pc <= io_idex_pc;
      exmem_reg_valid <= io_idex_valid;
      exmem_reg_rd_addr <= io_idex_rd_addr;
      exmem_reg_alu_result <= _alu_io_out;
      exmem_reg_rs2_data <= io_idex_rs2_data;
      exmem_reg_mem_en <= io_idex_mem_en;
      exmem_reg_mem_rw <= io_idex_mem_rw;
      exmem_reg_wb_sel <= io_idex_wb_sel;
      exmem_reg_reg_write <= io_idex_reg_write;
    end
  end // always @(posedge)
  ALU alu (
    .io_op  (io_idex_alu_op),
    .io_in1
      (io_idex_op1_sel == 2'h2
         ? io_idex_pc
         : (&io_idex_op1_sel) ? 32'h0 : io_idex_rs1_data),
    .io_in2
      (io_idex_op2_sel == 3'h2
         ? io_idex_imm
         : io_idex_op2_sel == 3'h3 ? 32'h4 : io_idex_rs2_data),
    .io_out (_alu_io_out)
  );
  assign io_exmem_pc = exmem_reg_pc;
  assign io_exmem_valid = exmem_reg_valid;
  assign io_exmem_rd_addr = exmem_reg_rd_addr;
  assign io_exmem_alu_result = exmem_reg_alu_result;
  assign io_exmem_rs2_data = exmem_reg_rs2_data;
  assign io_exmem_mem_en = exmem_reg_mem_en;
  assign io_exmem_mem_rw = exmem_reg_mem_rw;
  assign io_exmem_wb_sel = exmem_reg_wb_sel;
  assign io_exmem_reg_write = exmem_reg_reg_write;
  assign io_pc_target =
    io_idex_branch_type == 3'h0 ? io_idex_pc + io_idex_imm : {_jalr_target_T[31:1], 1'h0};
  assign io_pc_take = _GEN[io_idex_branch_type];
endmodule

