// Generated by CIRCT firtool-1.139.0
module ExecuteStage(
  input  [31:0] io_idex_pc,
  input         io_idex_valid,
  input  [4:0]  io_idex_rd_addr,
  input  [31:0] io_idex_rs1_data,
                io_idex_rs2_data,
                io_idex_imm,
  input  [1:0]  io_idex_op1_sel,
  input  [2:0]  io_idex_op2_sel,
  input  [3:0]  io_idex_alu_op,
  input  [2:0]  io_idex_branch_type,
  input         io_idex_mem_en,
                io_idex_mem_rw,
  input  [1:0]  io_idex_wb_sel,
  input         io_idex_reg_write,
  output [31:0] io_exmem_pc,
  output        io_exmem_valid,
  output [4:0]  io_exmem_rd_addr,
  output [31:0] io_exmem_alu_result,
                io_exmem_rs2_data,
  output        io_exmem_mem_en,
                io_exmem_mem_rw,
  output [1:0]  io_exmem_wb_sel,
  output        io_exmem_reg_write,
  output [31:0] io_pc_target,
  output        io_pc_take
);

  wire [7:0]  _GEN =
    {{&io_idex_branch_type},
     {io_idex_rs1_data >= io_idex_rs2_data},
     {$signed(io_idex_rs1_data) >= $signed(io_idex_rs2_data)},
     {io_idex_rs1_data < io_idex_rs2_data},
     {$signed(io_idex_rs1_data) < $signed(io_idex_rs2_data)},
     {io_idex_rs1_data != io_idex_rs2_data},
     {io_idex_rs1_data == io_idex_rs2_data},
     {&io_idex_branch_type}};
  wire [31:0] _jalr_target_T = io_idex_rs1_data + io_idex_imm;
  ALU alu (
    .io_op  (io_idex_alu_op),
    .io_in1
      (io_idex_op1_sel == 2'h2
         ? io_idex_pc
         : (&io_idex_op1_sel) ? 32'h0 : io_idex_rs1_data),
    .io_in2
      (io_idex_op2_sel == 3'h2
         ? io_idex_imm
         : io_idex_op2_sel == 3'h3 ? 32'h4 : io_idex_rs2_data),
    .io_out (io_exmem_alu_result)
  );
  assign io_exmem_pc = io_idex_pc;
  assign io_exmem_valid = io_idex_valid;
  assign io_exmem_rd_addr = io_idex_rd_addr;
  assign io_exmem_rs2_data = io_idex_rs2_data;
  assign io_exmem_mem_en = io_idex_mem_en;
  assign io_exmem_mem_rw = io_idex_mem_rw;
  assign io_exmem_wb_sel = io_idex_wb_sel;
  assign io_exmem_reg_write = io_idex_reg_write;
  assign io_pc_target =
    io_idex_op1_sel == 2'h1 ? {_jalr_target_T[31:1], 1'h0} : io_idex_pc + io_idex_imm;
  assign io_pc_take = _GEN[io_idex_branch_type];
endmodule

