// Generated by CIRCT firtool-1.139.0
module MemoryStage(
  input         clock,
                reset,
  input  [31:0] io_exmem_pc,
  input         io_exmem_valid,
  input  [4:0]  io_exmem_rd_addr,
  input  [31:0] io_exmem_alu_result,
                io_exmem_rs2_data,
  input         io_exmem_mem_en,
                io_exmem_mem_rw,
  input  [1:0]  io_exmem_wb_sel,
  input         io_exmem_reg_write,
  output [31:0] io_data_req_addr,
                io_data_req_wdata,
  output        io_data_req_wen,
                io_data_req_valid,
  input  [31:0] io_data_resp_rdata,
  output [31:0] io_memwb_pc,
  output        io_memwb_valid,
  output [4:0]  io_memwb_rd_addr,
  output [31:0] io_memwb_alu_result,
                io_memwb_mem_rdata,
  output [1:0]  io_memwb_wb_sel,
  output        io_memwb_reg_write
);

  reg [31:0] memwb_reg_pc;
  reg        memwb_reg_valid;
  reg [4:0]  memwb_reg_rd_addr;
  reg [31:0] memwb_reg_alu_result;
  reg [31:0] memwb_reg_mem_rdata;
  reg [1:0]  memwb_reg_wb_sel;
  reg        memwb_reg_reg_write;
  always @(posedge clock) begin
    if (reset) begin
      memwb_reg_pc <= 32'h0;
      memwb_reg_valid <= 1'h0;
      memwb_reg_rd_addr <= 5'h0;
      memwb_reg_alu_result <= 32'h0;
      memwb_reg_mem_rdata <= 32'h0;
      memwb_reg_wb_sel <= 2'h0;
      memwb_reg_reg_write <= 1'h0;
    end
    else begin
      memwb_reg_pc <= io_exmem_pc;
      memwb_reg_valid <= io_exmem_valid;
      memwb_reg_rd_addr <= io_exmem_rd_addr;
      memwb_reg_alu_result <= io_exmem_alu_result;
      memwb_reg_mem_rdata <= io_data_resp_rdata;
      memwb_reg_wb_sel <= io_exmem_wb_sel;
      memwb_reg_reg_write <= io_exmem_reg_write;
    end
  end // always @(posedge)
  assign io_data_req_addr = io_exmem_alu_result;
  assign io_data_req_wdata = io_exmem_rs2_data;
  assign io_data_req_wen = io_exmem_mem_rw;
  assign io_data_req_valid = io_exmem_mem_en;
  assign io_memwb_pc = memwb_reg_pc;
  assign io_memwb_valid = memwb_reg_valid;
  assign io_memwb_rd_addr = memwb_reg_rd_addr;
  assign io_memwb_alu_result = memwb_reg_alu_result;
  assign io_memwb_mem_rdata = memwb_reg_mem_rdata;
  assign io_memwb_wb_sel = memwb_reg_wb_sel;
  assign io_memwb_reg_write = memwb_reg_reg_write;
endmodule

